version: '3'
services:
  dhf4-server:
    build: "./src/main/docker/marklogic"
    image: "marklogic:9.0-7"
    ports:
    # choose what ports you want to expose (at least 8000 8001 8002)
      - "8000-8050:8000-8050"
    hostname: "dhf4-server.local"
    container_name: "dhf4-server.local"
    volumes:
       - ./logs/dhf4-server:/var/opt/MarkLogic/Logs

# optionally specify the subnet
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.61.0.0/16