version: '3'
services:
  dhf412:
    build: "./src/main/docker/marklogic"
    image: "marklogic:9.0-7.2"
    ports:
    # choose what ports you want to expose (at least 8000 8001 8002)
      - "8000-8050:8000-8050"
    hostname: "dhf41.local"
    container_name: "dhf41.local"
    volumes:
       - ./logs/dhf41:/var/opt/MarkLogic/Logs

# optionally specify the subnet
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.17.0.0/16